export interface Car {
  id: number,
  brand: string,
  model: string,
  year: number | string,
  gearbox: string,
  mileage: number,
  engineFuelType: string,
  engineVolume: number,
  enginePower: number,
  vrc: "original" | "copy",
  steeringWheel: "left" | "right",
  price: number,
  loanPrice: number,
  specialType: string,
}